/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package backstage;

import backstage.Customer;
import backstage.StockAccount;
import backstage.Tool;
import static backstage.StockAccount.LEASTBALANCE;
import static backstage.StockAccount.LEASTMONEY;
import connect_database.CustomerAddingFunction;
import connect_database.CustomerAlteringFunction;
import connect_database.ManagerFunction;
import java.math.BigDecimal;

/**
 *
 * @author user
 */
public class OpenStockJFrame extends javax.swing.JFrame {

    private Customer customer;
    private StockAccount account;
    private boolean createAccount;

    /**
     * Creates new form OpenStockJFrame
     */
    public OpenStockJFrame(Customer customer, StockAccount account) {
        this.customer = customer;
        this.account = account;
        this.createAccount = false;
        initComponents();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saveTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter money (at least $1000) to start a stock account:");

        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        errorLabel.setText("          ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(saveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (createAccount) {
            errorLabel.setText("There is already a stock account.");
        }
        else {
            String cashStr = saveTextField.getText();
            if (!Tool.is_number(cashStr)) {
                errorLabel.setText("Invalid save input. Please input a number.");
            }
            else {
                boolean success = account.currency.sub("Dollar", 5, "1");
                if (success) {
                    String[] cash = account.withdraw(cashStr, "Dollar",
                                                     LEASTMONEY,
                                                     LEASTBALANCE);
                    if (cash[0].equals("")) {
                        errorLabel.setText(
                                "Failed to create stock account. Check your savings.");
                    }
                    else {
                        //alter manager
                        ManagerFunction.alterManagerAccount("Dollar",
                                                            new BigDecimal("5"));
                        //add stock account in database
                        CustomerAddingFunction.addStockAccount(
                                account.customerID);
                        BigDecimal cap = new BigDecimal(cash[0]);
                        cap = cap.add(new BigDecimal(cash[1]));
                        CustomerAlteringFunction.alterSavingAccount(
                                account.customerID,
                                "Dollar",
                                new BigDecimal(
                                        "-5"));
                        CustomerAlteringFunction.alterSavingAccount(
                                account.customerID,
                                "Dollar",
                                new BigDecimal(
                                        "-" + cap.toString()));
                        CustomerAlteringFunction.alterStockAccount(
                                account.customerID,
                                new BigDecimal(
                                        cash[0]));
                        ManagerFunction.alterManagerAccount("Dollar",
                                                            new BigDecimal(
                                                                    cash[1]));
                        account.createTransaction("-5", "Dollar",
                                                  "Open Stock account.");
                        account.createTransaction(cap.toString(), "Dollar",
                                                  "Stock account capital.");

                        customer.accounts.add(account);
                        errorLabel.setText(
                                "Successfully create stock account with a charge of $5.");
                        createAccount = true;
                    }
                }
                else {
                    errorLabel.setText(
                            "You don't have $5. Fail to open stock account.");
                    account.createTransaction("0", "Dollar",
                                              "Failed to open stock account.");
                    account.currency.sub("Dollar", Double.parseDouble(cashStr),
                                         "1");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpenStockJFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpenStockJFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpenStockJFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenStockJFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField saveTextField;
    // End of variables declaration//GEN-END:variables
}
